/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rys;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author HP
 */
public class RestoranYonetimSistemi extends javax.swing.JFrame {
    
    double firstnum,secondnum,result=0;
    int[]yiyecek_fiyat={250 ,300 ,500 ,350};
    int[]icecek_fiyat={75 ,50 ,75 ,60};
    double kdv=0,servis=0,yiyecek_total=0,icecek_total=0;
    double aratoplam=0, geneltoplam=0;
    String operatör="";


    public RestoranYonetimSistemi() {
        initComponents();
    }
public double hesaplaIfade(String ifade) {
    ifade = ifade.replaceAll("\\s+", ""); // boşlukları sil

    double sayi1 = 0, sayi2 = 0;
    char islem = ' ';
    int islemIndex = -1;

    // işlemi bul
    for (int i = 0; i < ifade.length(); i++) {
        char c = ifade.charAt(i);
        if (c == '+' || c == '-' || c == '*' || c == '/'||c=='%') {
            islem = c;
            islemIndex = i;
            break;
        }
    }

    if (islemIndex == -1) {
        // işlem yok, doğrudan sayı girilmiş
        return Double.parseDouble(ifade);
    }

    try {
        sayi1 = Double.parseDouble(ifade.substring(0, islemIndex));
        sayi2 = Double.parseDouble(ifade.substring(islemIndex + 1));
    } catch (Exception e) {
        return 0;
    }

    switch (islem) {
        case'%':return sayi1%sayi2;
        case '+': return sayi1 + sayi2;
        case '-': return sayi1 - sayi2;
        case '*': return sayi1 * sayi2;
        case '/': return sayi2 != 0 ? sayi1 / sayi2 : 0; // 0'a bölme hatası kontrolü
        default: return 0;
    }
}
    
     public void guncelleToplam() {
        aratoplam = yiyecek_total + icecek_total;
        servis = aratoplam * 0.10;
        kdv = aratoplam * 0.08;
        geneltoplam = aratoplam + servis + kdv;

        // Ekrandaki label'ları güncelleyin (ID'leri sizde farklıysa değiştirin)
        lbl_servis.setText(String.format("₺%.2f", servis));
        lbl_kdv.setText(String.format("₺%.2f", kdv));
        lbl_geneltoplam.setText(String.format("₺%.2f", geneltoplam));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_tavuk = new javax.swing.JCheckBox();
        cb_et = new javax.swing.JCheckBox();
        cb_iskender = new javax.swing.JCheckBox();
        txt_tavuk = new javax.swing.JTextField();
        txt_et = new javax.swing.JTextField();
        txt_iskender = new javax.swing.JTextField();
        cb_burdursis = new javax.swing.JCheckBox();
        txt_burdursis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_aratoplam = new javax.swing.JLabel();
        lbl_kdv = new javax.swing.JLabel();
        lbl_geneltoplam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cb_kola = new javax.swing.JCheckBox();
        cb_ayran = new javax.swing.JCheckBox();
        cb_soda = new javax.swing.JCheckBox();
        cb_salgam = new javax.swing.JCheckBox();
        txt_kola = new javax.swing.JTextField();
        txt_ayran = new javax.swing.JTextField();
        txt_salgam = new javax.swing.JTextField();
        txt_soda = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_icecek = new javax.swing.JLabel();
        lbl_yiyecek = new javax.swing.JLabel();
        lbl_servis = new javax.swing.JLabel();
        cb_servis = new javax.swing.JCheckBox();
        cb_kdv = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        txt_ekran = new javax.swing.JTextField();
        b_del = new javax.swing.JButton();
        b_c = new javax.swing.JButton();
        b_artıeksi = new javax.swing.JButton();
        b_toplama = new javax.swing.JButton();
        b_7 = new javax.swing.JButton();
        b_8 = new javax.swing.JButton();
        b_9 = new javax.swing.JButton();
        b_cikartma = new javax.swing.JButton();
        b_4 = new javax.swing.JButton();
        b_5 = new javax.swing.JButton();
        b_6 = new javax.swing.JButton();
        b_carpma = new javax.swing.JButton();
        b_3 = new javax.swing.JButton();
        b_2 = new javax.swing.JButton();
        b_1 = new javax.swing.JButton();
        b_bolme = new javax.swing.JButton();
        b_0 = new javax.swing.JButton();
        b_nokta = new javax.swing.JButton();
        b_esittir = new javax.swing.JButton();
        b_mod = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_fatura = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn_toplam = new javax.swing.JButton();
        btn_fatura = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_kapat = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        cb_tavuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_tavuk.setText("Tavuk Döner");
        cb_tavuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tavukActionPerformed(evt);
            }
        });

        cb_et.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_et.setText("Et döner");
        cb_et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_etActionPerformed(evt);
            }
        });

        cb_iskender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_iskender.setText("İskender");
        cb_iskender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_iskenderActionPerformed(evt);
            }
        });

        txt_tavuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_tavuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tavukActionPerformed(evt);
            }
        });

        txt_et.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txt_iskender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cb_burdursis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_burdursis.setText("Burdur Şiş");
        cb_burdursis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_burdursisActionPerformed(evt);
            }
        });

        txt_burdursis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_et)
                            .addComponent(cb_iskender)
                            .addComponent(cb_tavuk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_burdursis)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_burdursis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_iskender, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_et, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_tavuk, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tavuk)
                    .addComponent(txt_tavuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_et)
                    .addComponent(txt_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_iskender)
                    .addComponent(txt_iskender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_burdursis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_burdursis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ara Toplam");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("KDV");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Genel Toplam");

        lbl_aratoplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_kdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_geneltoplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_aratoplam, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(lbl_kdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_geneltoplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_aratoplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_kdv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_geneltoplam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        cb_kola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_kola.setText("Kola");
        cb_kola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kolaActionPerformed(evt);
            }
        });

        cb_ayran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_ayran.setText("Ayran");
        cb_ayran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ayranActionPerformed(evt);
            }
        });

        cb_soda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_soda.setText("Soda");
        cb_soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sodaActionPerformed(evt);
            }
        });

        cb_salgam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_salgam.setText("Şalgam");
        cb_salgam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_salgamActionPerformed(evt);
            }
        });

        txt_kola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_kola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kolaActionPerformed(evt);
            }
        });

        txt_ayran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_ayran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ayranActionPerformed(evt);
            }
        });

        txt_salgam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_salgam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salgamActionPerformed(evt);
            }
        });

        txt_soda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sodaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_salgam)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_ayran)
                            .addComponent(cb_soda))
                        .addComponent(cb_kola)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ayran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_salgam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_kola)
                    .addComponent(txt_kola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_ayran)
                    .addComponent(txt_ayran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_soda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_soda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_salgam)
                    .addComponent(txt_salgam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("İçecek ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Yiyecek");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Servis");

        lbl_icecek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_yiyecek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_servis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cb_servis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_servis.setText("Servis Bedeli");
        cb_servis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_servisActionPerformed(evt);
            }
        });

        cb_kdv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_kdv.setText("KDV");
        cb_kdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kdvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cb_servis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_kdv)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_yiyecek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_servis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_icecek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_icecek, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_yiyecek, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_servis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_servis)
                    .addComponent(cb_kdv)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        txt_ekran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ekran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ekranActionPerformed(evt);
            }
        });

        b_del.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_del.setText("Del");
        b_del.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_delActionPerformed(evt);
            }
        });

        b_c.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_c.setText("C");
        b_c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cActionPerformed(evt);
            }
        });

        b_artıeksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_artıeksi.setText("+/-");
        b_artıeksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_artıeksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_artıeksiActionPerformed(evt);
            }
        });

        b_toplama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_toplama.setText("+");
        b_toplama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_toplama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_toplamaActionPerformed(evt);
            }
        });

        b_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_7.setText("7");
        b_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_7ActionPerformed(evt);
            }
        });

        b_8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_8.setText("8");
        b_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_8ActionPerformed(evt);
            }
        });

        b_9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_9.setText("9");
        b_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_9ActionPerformed(evt);
            }
        });

        b_cikartma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_cikartma.setText("-");
        b_cikartma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_cikartma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cikartmaActionPerformed(evt);
            }
        });

        b_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_4.setText("4");
        b_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4ActionPerformed(evt);
            }
        });

        b_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_5.setText("5");
        b_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_5ActionPerformed(evt);
            }
        });

        b_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_6.setText("6");
        b_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_6ActionPerformed(evt);
            }
        });

        b_carpma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_carpma.setText("*");
        b_carpma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_carpma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_carpmaActionPerformed(evt);
            }
        });

        b_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_3.setText("3");
        b_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_3ActionPerformed(evt);
            }
        });

        b_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_2.setText("2");
        b_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2ActionPerformed(evt);
            }
        });

        b_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_1.setText("1");
        b_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1ActionPerformed(evt);
            }
        });

        b_bolme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_bolme.setText("/");
        b_bolme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_bolme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bolmeActionPerformed(evt);
            }
        });

        b_0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_0.setText("0");
        b_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_0ActionPerformed(evt);
            }
        });

        b_nokta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_nokta.setText(".");
        b_nokta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_nokta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_noktaActionPerformed(evt);
            }
        });

        b_esittir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_esittir.setText("=");
        b_esittir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_esittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_esittirActionPerformed(evt);
            }
        });

        b_mod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_mod.setText("%");
        b_mod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b_del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_c, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(b_artıeksi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_toplama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 57, Short.MAX_VALUE))
                            .addComponent(txt_ekran))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(b_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(b_9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_cikartma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(b_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_carpma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(b_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_bolme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_nokta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(b_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_artıeksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_toplama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_cikartma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_carpma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_bolme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_nokta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hesap Makinesi", jPanel6);

        txtarea_fatura.setColumns(20);
        txtarea_fatura.setRows(5);
        jScrollPane1.setViewportView(txtarea_fatura);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fatura", jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Restoran Yönetim Sistemi");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        btn_toplam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_toplam.setText("Toplam");
        btn_toplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_toplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamActionPerformed(evt);
            }
        });

        btn_fatura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_fatura.setText("Fatura");
        btn_fatura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_fatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaActionPerformed(evt);
            }
        });

        btn_sil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sil.setText("Sil");
        btn_sil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_kapat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_kapat.setText("Kapat");
        btn_kapat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kapatActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_toplam)
                    .addComponent(btn_fatura)
                    .addComponent(btn_sil)
                    .addComponent(btn_reset)
                    .addComponent(btn_kapat))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(568, 568, 568))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tavukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tavukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tavukActionPerformed

    private void txt_kolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kolaActionPerformed
     private void yiyecek_hesap(javax.swing.JCheckBox cb,javax.swing.JTextField txt,int fiyat_index){
            if(cb.isSelected() && txt.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Lütfem bir değer giriniz!");
                cb.setSelected(false);
                return;
            }
            int yiyecek_adet;
            try{
                   yiyecek_adet=Integer.parseInt(txt.getText());
                   if(yiyecek_adet<0){
                       JOptionPane.showMessageDialog(null,"Lütfen 0'dan Büyük Bir Sayı Giriniz");
                       cb.setSelected(false);//seçilen yanlış sayıyı silip tekrar değer girmek için hazır hale getirir
                       txt.setText("");
                       return;
                   }
                   
               }
               catch(Exception ex){
                   JOptionPane.showMessageDialog(null,"Lütfen sayısal değer biriniz");
                   return;
               }
              ;
    if(cb.isSelected()){
        yiyecek_total+=yiyecek_adet*yiyecek_fiyat[fiyat_index];
    }else{
          yiyecek_total-=yiyecek_adet*yiyecek_fiyat[0];// TODO add your handling code here:
    }                                     
          lbl_yiyecek.setText(String.format("%.2f TL",yiyecek_total));
     }
     private void islem(String opt){
         firstnum=Double.parseDouble(txt_ekran.getText());
         operatör=opt;
         txt_ekran.setText("");
        
         
         
         
     }
     private void icecek_hesap(javax.swing.JCheckBox cb,javax.swing.JTextField txt,int fiyat_index){
                     if(cb.isSelected() && txt.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Lütfem bir değer giriniz!");
                cb.setSelected(false);
                return;
            }
               int icecek_adet;
               try{
                   icecek_adet=Integer.parseInt(txt.getText());
                   
               }
               catch(Exception ex){
                   JOptionPane.showMessageDialog(null,"Lütfen sayısal değer biriniz");
                   return;
               }
               
    if(cb.isSelected()){
        icecek_total+=icecek_adet*icecek_fiyat[fiyat_index];
    }else{
          icecek_total-=icecek_adet*icecek_fiyat[0];// TODO add your handling code here:
    }                                     
          lbl_icecek.setText(String.format("%.2f TL",icecek_total));
     }
    private void cb_tavukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tavukActionPerformed
       yiyecek_hesap(cb_tavuk,txt_tavuk,0);
        
    }//GEN-LAST:event_cb_tavukActionPerformed

    private void cb_etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_etActionPerformed
        yiyecek_hesap(cb_et,txt_et,0);
    }//GEN-LAST:event_cb_etActionPerformed
         
    
    private void cb_iskenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_iskenderActionPerformed
      yiyecek_hesap(cb_iskender,txt_iskender,0);
     
    }//GEN-LAST:event_cb_iskenderActionPerformed

    private void cb_burdursisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_burdursisActionPerformed
          yiyecek_hesap(cb_burdursis,txt_burdursis,0);
    }//GEN-LAST:event_cb_burdursisActionPerformed

    private void txt_ayranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ayranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ayranActionPerformed

    private void txt_sodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sodaActionPerformed

    private void txt_salgamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salgamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salgamActionPerformed

    private void cb_kolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kolaActionPerformed
      icecek_hesap(cb_kola,txt_kola,0);  // TODO add your handling code here:
    }//GEN-LAST:event_cb_kolaActionPerformed

    private void cb_ayranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ayranActionPerformed
      icecek_hesap(cb_ayran,txt_ayran,0);  // TODO add your handling code here:
    }//GEN-LAST:event_cb_ayranActionPerformed

    private void cb_sodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sodaActionPerformed
       icecek_hesap(cb_soda,txt_soda,0); // TODO add your handling code here:
    }//GEN-LAST:event_cb_sodaActionPerformed

    private void cb_salgamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_salgamActionPerformed
      icecek_hesap(cb_salgam,txt_salgam,0);  // TODO add your handling code here:
    }//GEN-LAST:event_cb_salgamActionPerformed

    private void cb_servisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_servisActionPerformed
        if(cb_servis.isSelected()){
       servis=(yiyecek_total +icecek_total)*0.10;
       lbl_servis.setText(String.format("%.2f TL",servis));
        }
       else{
        servis=0;
        kdv=0;
        cb_kdv.setSelected(false);
        lbl_kdv.setText("");      
        lbl_servis.setText("");
         
        }  
    }//GEN-LAST:event_cb_servisActionPerformed
      
    private void cb_kdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kdvActionPerformed
        if(cb_servis.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Lütfen önce servis bedelini hesaplatınız");
            cb_kdv.setSelected(false);
            return;
        }
        if(cb_kdv.isSelected()){
         
         kdv=(yiyecek_total+icecek_total+kdv)*0.18;
         lbl_kdv.setText(String.format("%.2f Tl",kdv));
        }
         else{
          kdv=0;
          lbl_kdv.setText(" "); 
    }//GEN-LAST:event_cb_kdvActionPerformed
}
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
   txt_tavuk.setText(""); txt_ayran.setText(""); txt_soda.setText(""); txt_kola.setText(""); txt_salgam.setText(""); txt_iskender.setText(""); txt_burdursis.setText(""); txt_iskender.setText("");
   cb_tavuk.setSelected(false); cb_ayran.setSelected(false); cb_soda.setSelected(false); cb_kola.setSelected(false); cb_salgam.setSelected(false); cb_iskender.setSelected(false); cb_burdursis.setSelected(false); 
   cb_servis.setSelected(false);
   cb_kdv.setSelected(false);
   lbl_aratoplam.setText("");
   lbl_geneltoplam.setText("");
   lbl_kdv.setText("");
   lbl_icecek.setText("");
   lbl_yiyecek.setText("");
   lbl_servis.setText("");
   txtarea_fatura.setText("");

    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_toplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamActionPerformed
        if(cb_kdv.isSelected()){
            aratoplam=yiyecek_total+icecek_total+servis;
            geneltoplam=aratoplam+kdv;
            lbl_aratoplam.setText(String.format("%.2f TL",aratoplam));
            lbl_geneltoplam.setText(String.format("%.2f TL",geneltoplam));

            
}
    else{
    JOptionPane.showMessageDialog(null,"lütfen önce kdv hesaplayınız");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_toplamActionPerformed
   }
    private void btn_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kapatActionPerformed
    dispose();

    }//GEN-LAST:event_btn_kapatActionPerformed

    private void b_artıeksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_artıeksiActionPerformed
         String mevcut = txt_ekran.getText();
    
    if (!mevcut.isEmpty()) {
        try {
            // Mevcut metni bir sayıya dönüştür
            double sayi = Double.parseDouble(mevcut);
            
            // Sayının işaretini değiştir
            sayi = -sayi;
            
            // Yeni sayıyı ekrana yaz
            txt_ekran.setText(String.valueOf(sayi));
        } catch (NumberFormatException e) {
            // Eğer metin bir sayıya dönüştürülemezse (örneğin boş veya geçersiz bir girişse)
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir sayı giriniz!");
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_b_artıeksiActionPerformed

    private void b_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_9ActionPerformed
       goruntuleme(b_9); // TODO add your handling code here:
    }//GEN-LAST:event_b_9ActionPerformed

    private void b_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_6ActionPerformed
      goruntuleme(b_6);  // TODO add your handling code here:
    }//GEN-LAST:event_b_6ActionPerformed

    private void b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1ActionPerformed
       goruntuleme(b_1); // TODO add your handling code here:
    }//GEN-LAST:event_b_1ActionPerformed

    private void b_esittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_esittirActionPerformed
        secondnum=Double.parseDouble(txt_ekran.getText());
        if(operatör.equals("Toplama")){
            result=firstnum+secondnum;
        }
        else if(operatör.equals("Cikarma")){
            result=firstnum-secondnum;
        }
        else if(operatör.equals("Carpma")){
            result=firstnum*secondnum;
        }
        else if(operatör.equals("Bolme")){
            result=firstnum/secondnum;         
        }
        else if(operatör.equals("Mod")){
            result=firstnum%secondnum;
        }
        txt_ekran.setText(String.valueOf(result));
    }//GEN-LAST:event_b_esittirActionPerformed
     void goruntuleme(javax.swing.JButton btn){
         
         String tmp=txt_ekran.getText();
         if(tmp.equals("0")){
             tmp=btn.getText();
         }
         else{
             tmp+=btn.getText();
         }
         txt_ekran.setText(tmp);
         
     }
    private void b_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_7ActionPerformed
    String tmp=txt_ekran.getText();        // TODO add your handling code here:
    tmp+=b_7.getText();
    txt_ekran.setText(tmp);
    }//GEN-LAST:event_b_7ActionPerformed

    private void b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2ActionPerformed
       goruntuleme(b_2); // TODO add your handling code here:
    }//GEN-LAST:event_b_2ActionPerformed

    private void b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_3ActionPerformed
    goruntuleme(b_3);        // TODO add your handling code here:
    }//GEN-LAST:event_b_3ActionPerformed

    private void b_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4ActionPerformed
    goruntuleme(b_4);        // TODO add your handling code here:
    }//GEN-LAST:event_b_4ActionPerformed

    private void b_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_5ActionPerformed
        goruntuleme(b_5);        // TODO add your handling code here:
    }//GEN-LAST:event_b_5ActionPerformed

    private void b_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_8ActionPerformed
        goruntuleme(b_8);        // TODO add your handling code here:
    }//GEN-LAST:event_b_8ActionPerformed

    private void b_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_0ActionPerformed
        if(txt_ekran.getText().equals("")){
            goruntuleme(b_0);
            return;
        }
        StringBuffer stb=new StringBuffer(txt_ekran.getText());
        if(stb.charAt(0)!='0'||stb.indexOf(".")!=-1){//ilk karakterde 0 yoksa veya . yoksa
        goruntuleme(b_0);
        
            
            
        }
        
        
       // TODO add your handling code here:
    }//GEN-LAST:event_b_0ActionPerformed

    private void b_toplamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_toplamaActionPerformed
     try
     {
      islem("Toplama");
    }//GEN-LAST:event_b_toplamaActionPerformed
      catch(Exception ex){
          JOptionPane.showMessageDialog(null,"Lütfen Sayısal Bir İfade Girinizi");
          txt_ekran.setText("");
      }
    }
    private void b_cikartmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cikartmaActionPerformed
    islem("Cikarma");

    }//GEN-LAST:event_b_cikartmaActionPerformed

    private void b_carpmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_carpmaActionPerformed
   islem("Carpma");

    }//GEN-LAST:event_b_carpmaActionPerformed

    private void b_bolmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bolmeActionPerformed
     islem("Bolme");

    }//GEN-LAST:event_b_bolmeActionPerformed

    private void b_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_delActionPerformed
      String mevcut=txt_ekran.getText();
      if (!mevcut.isEmpty()) {
        txt_ekran.setText(mevcut.substring(0, mevcut.length() - 1));
    }
      else {
          JOptionPane.showMessageDialog(null, "Lütfen geçerli bir sayı giriniz!");
         
      }
          
      
    }//GEN-LAST:event_b_delActionPerformed

    private void b_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cActionPerformed
      txt_ekran.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_b_cActionPerformed

    private void b_noktaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_noktaActionPerformed
    StringBuffer stb=new StringBuffer(txt_ekran.getText());
    if(stb.indexOf(".")==-1){
        stb.append(".");
        txt_ekran.setText(stb.toString());
        
    }
  
    }//GEN-LAST:event_b_noktaActionPerformed

    private void b_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modActionPerformed
    islem("Mod");   // TODO add your handling code here:
    }//GEN-LAST:event_b_modActionPerformed

    private void btn_faturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaActionPerformed
     if(geneltoplam!=0){
         txtarea_fatura.append("FATURA:\n\n"+
          "Fatura Tarihi:\t"+LocalDate.now()+
          "\nİçcecek Fiytatı:\t"+lbl_icecek.getText()+
          "\nYemek Fiytatı:\t"+lbl_yiyecek.getText()+
          "\nAra Toplam :\t"+lbl_aratoplam.getText()+
          "\nKDV :\t"+lbl_kdv.getText()+
          "\nGenel Toplam:\t"+lbl_geneltoplam.getText() );       

    }//GEN-LAST:event_btn_faturaActionPerformed
    else{
    JOptionPane.showMessageDialog(null,"Lütfen toplamı hesaplatınız");
    }
}   
    private void txt_ekranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ekranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ekranActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoranYonetimSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoranYonetimSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoranYonetimSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoranYonetimSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestoranYonetimSistemi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_0;
    private javax.swing.JButton b_1;
    private javax.swing.JButton b_2;
    private javax.swing.JButton b_3;
    private javax.swing.JButton b_4;
    private javax.swing.JButton b_5;
    private javax.swing.JButton b_6;
    private javax.swing.JButton b_7;
    private javax.swing.JButton b_8;
    private javax.swing.JButton b_9;
    private javax.swing.JButton b_artıeksi;
    private javax.swing.JButton b_bolme;
    private javax.swing.JButton b_c;
    private javax.swing.JButton b_carpma;
    private javax.swing.JButton b_cikartma;
    private javax.swing.JButton b_del;
    private javax.swing.JButton b_esittir;
    private javax.swing.JButton b_mod;
    private javax.swing.JButton b_nokta;
    private javax.swing.JButton b_toplama;
    private javax.swing.JButton btn_fatura;
    private javax.swing.JButton btn_kapat;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_toplam;
    private javax.swing.JCheckBox cb_ayran;
    private javax.swing.JCheckBox cb_burdursis;
    private javax.swing.JCheckBox cb_et;
    private javax.swing.JCheckBox cb_iskender;
    private javax.swing.JCheckBox cb_kdv;
    private javax.swing.JCheckBox cb_kola;
    private javax.swing.JCheckBox cb_salgam;
    private javax.swing.JCheckBox cb_servis;
    private javax.swing.JCheckBox cb_soda;
    private javax.swing.JCheckBox cb_tavuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_aratoplam;
    private javax.swing.JLabel lbl_geneltoplam;
    private javax.swing.JLabel lbl_icecek;
    private javax.swing.JLabel lbl_kdv;
    private javax.swing.JLabel lbl_servis;
    private javax.swing.JLabel lbl_yiyecek;
    private javax.swing.JTextField txt_ayran;
    private javax.swing.JTextField txt_burdursis;
    private javax.swing.JTextField txt_ekran;
    private javax.swing.JTextField txt_et;
    private javax.swing.JTextField txt_iskender;
    private javax.swing.JTextField txt_kola;
    private javax.swing.JTextField txt_salgam;
    private javax.swing.JTextField txt_soda;
    private javax.swing.JTextField txt_tavuk;
    private javax.swing.JTextArea txtarea_fatura;
    // End of variables declaration//GEN-END:variables
}
